/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-110422-g7b2851b290-20230430"
#endif /* AVUTIL_FFVERSION_H */
